### ISSUE TITLE
Arrow extension error

### ISSUE THREAD

**Issue by KrishnaPG** [uwdata/mosaic#132] opened 2023-07-18 09:19 UTC
When running the below command for the first time after cloning and building the code,
```sh
npm run server
```
getting the below error:
```
[Error: HTTP Error: Failed to download extension "arrow" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64/arrow.duckdb_extension.gz"

Candidate extensions: "parquet"] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'HTTP',
  statusCode: 403,
  response: '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>0PPQ3MBV0ZF6S049</RequestId><HostId>vtgA1i3BYRWWN3uagdtM2uxLv5xfAz4th9XajMjrtTwtuxqK+EJ9n2IH4bZkjqyXH1kplh66mhk=</HostId></Error>',
  reason: 'Forbidden',
  headers: {
    Connection: 'close',
    'Content-Type': 'application/xml',
    Date: 'Tue, 18 Jul 2023 09:04:38 GMT',
    Server: 'AmazonS3',
    'Transfer-Encoding': 'chunked',
    Via: '1.1 dc76840562be68c0220fc72e79c212b8.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'tcxRBgZSrHjye30qgyTF13OJPDt8cjQB2YgvciWh632LuM3irYPGKw==',
    'X-Amz-Cf-Pop': 'HYD50-C1',
    'X-Cache': 'Error from cloudfront'
  }
}

```

**Comment by domoritz** [comment] 2023-07-18 12:34
Duplicate of https://github.com/duckdb/duckdb/issues/6404.

**Closed by domoritz** 2023-07-18 12:34 UTC
