### ISSUE TITLE
Support histograms

### ISSUE THREAD

**Issue by maelp** [uwdata/mosaic#283] opened 2024-01-31 21:42 UTC
It's not clear from the documentation how to support histogram plots, is it possible out-of-the-box, or do we need to do our own binning and then use a bar chart?

I think it's one of the most widespread graph, might be useful to have a few examples in the documentation

**Comment by jheer** [comment] 2024-01-31 21:49
Here is an existing example (among others) consisting of three linked histograms:
https://uwdata.github.io/mosaic/examples/flights-200k.html

And yes, the current model is to perform binning and create a bar chart.

Agreed that the documentation might benefit from a simpler example with "Histogram" in the name!

**Comment by maelp** [comment] 2024-01-31 21:52
Thanks!

**Comment by domoritz** [comment] 2024-01-31 21:56
I think it would also help to make the distinction between Mosaic and vgplot clearer. The introduction is very good about talking about Mosaic, what it is and how it works, but maybe we can be more explicit about the fact that vgplot is not the only way to use Mosaic.

**Comment by maelp** [comment] 2024-01-31 22:03
I agree

and also how to easily build “escape hatch” to use any methods from
vega-lite / observable from Mosaic would be useful

**Comment by domoritz** [comment] 2024-01-31 23:16
Can you elaborate? We already explain extensibility in https://uwdata.github.io/mosaic/why-mosaic/#mosaic-is-extensible and have docs for building clients at https://uwdata.github.io/mosaic/core/#clients.

**Comment by Unemyr** [comment] 2024-02-05 06:06
Another example that would be really fantastic would be to understand how to bin timestamp data. There are some really good examples on how to plot data by day of week, or month in year. But I just cant get a linear timescale to plot.

vgplot.bin() throws an error "Binder Error: No function matches the given name and argument types '-(TIMESTAMP, BIGINT)' when you try to do that for example with the rectY mark. You might need to add explicit type casts.". Perhaps there is something really rudimentary I am missing, in order to get that to work?

I am able to get an areaY to render with timescale data, but I believe from performance reasons it would be significantly better to have the data binned first.

**Comment by jheer** [comment] 2024-02-06 20:02
Hi @Unemyr, this is the direction I would recommend. The vgplot `bin` transform is specifically focused on binning quantitative values, and by design it does not operate on date-time data and related intervals (year, quarter, month, etc). I'd recommend opening a new feature request issue for support for time bin functions that produce the desired intervals (not unlike what Vega-Lite provides). We'd also be happy to review PRs along these lines.

**Comment by Unemyr** [comment] 2024-02-06 22:20
OK noted on that. I would be open to contributing PRs for that later. Thanks for the quick reply!

**Comment by domoritz** [comment] 2024-05-23 14:05
I'll close this for now since mosaic supports histograms.

**Closed by domoritz** 2024-05-23 14:05 UTC
Labels: documentation
